/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/attachments/": {
    get: operations["api_attachments_list"];
    post: operations["api_attachments_create"];
  };
  "/api/attachments/{id}/": {
    get: operations["api_attachments_retrieve"];
    put: operations["api_attachments_update"];
    delete: operations["api_attachments_destroy"];
    patch: operations["api_attachments_partial_update"];
  };
  "/api/attachments/attachment-groups/": {
    get: operations["api_attachments_attachment_groups_list"];
  };
  "/api/attachments/attachment-groups/{id}/": {
    get: operations["api_attachments_attachment_groups_retrieve"];
  };
  "/api/attachments/attachment-groups/{id}/attachments/": {
    /** @description Action for update or delete attachments */
    put: operations["api_attachments_attachment_groups_attachments_update"];
    /** @description Action for update or delete attachments */
    delete: operations["api_attachments_attachment_groups_attachments_destroy"];
  };
  "/api/auth/login/": {
    /**
     * @description Check the credentials and return the REST Token
     * if the credentials are valid and authenticated.
     * Calls Django Auth login method to register User ID
     * in Django session framework
     *
     * Accept the following POST parameters: username, password
     * Return the REST Framework Token Object's key.
     */
    post: operations["api_auth_login_create"];
  };
  "/api/auth/logout/": {
    /**
     * @description Calls Django logout method and delete the Token object
     * assigned to the current User object.
     *
     * Accepts/Returns nothing.
     */
    post: operations["api_auth_logout_create"];
  };
  "/api/auth/password/change/": {
    /**
     * @description Calls Django Auth SetPasswordForm save method.
     *
     * Accepts the following POST parameters: new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["api_auth_password_change_create"];
  };
  "/api/auth/password/reset/": {
    /**
     * @description Calls Django Auth PasswordResetForm save method.
     *
     * Accepts the following POST parameters: email
     * Returns the success/fail message.
     */
    post: operations["api_auth_password_reset_create"];
  };
  "/api/auth/password/reset/confirm/": {
    /**
     * @description Password reset e-mail link is confirmed, therefore
     * this resets the user's password.
     *
     * Accepts the following POST parameters: token, uid,
     *     new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["api_auth_password_reset_confirm_create"];
  };
  "/api/auth/registration/": {
    post: operations["api_auth_registration_create"];
  };
  "/api/auth/registration/resend-email/": {
    post: operations["api_auth_registration_resend_email_create"];
  };
  "/api/auth/registration/verify-email/": {
    post: operations["api_auth_registration_verify_email_create"];
  };
  "/api/auth/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["api_auth_token_refresh_create"];
  };
  "/api/auth/token/verify/": {
    /**
     * @description Takes a token and indicates if it is valid.  This view provides no
     * information about a token's fitness for a particular use.
     */
    post: operations["api_auth_token_verify_create"];
  };
  "/api/auth/user/": {
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    get: operations["api_auth_user_retrieve"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    put: operations["api_auth_user_update"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    patch: operations["api_auth_user_partial_update"];
  };
  "/api/bot/": {
    post: operations["api_bot_create"];
  };
  "/api/games/": {
    get: operations["api_games_list"];
  };
  "/api/games/{game_pk}/tournaments/": {
    get: operations["api_games_tournaments_list"];
  };
  "/api/games/{game_pk}/tournaments/{id}/": {
    get: operations["api_games_tournaments_retrieve"];
  };
  "/api/games/{game_pk}/tournaments/{id}/finish/": {
    post: operations["api_games_tournaments_finish_create"];
  };
  "/api/games/{game_pk}/tournaments/{id}/scores/": {
    /** @description Returns scores for tournament */
    get: operations["api_games_tournaments_scores_retrieve"];
  };
  "/api/games/{game_pk}/tournaments/{id}/start/": {
    post: operations["api_games_tournaments_start_create"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/matches/{match_pk}/periods/": {
    get: operations["api_games_tournaments_matches_periods_list"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/matches/{match_pk}/periods/{period_pk}/scores/{id}/": {
    put: operations["api_games_tournaments_matches_periods_scores_update"];
    patch: operations["api_games_tournaments_matches_periods_scores_partial_update"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/matches/{match_pk}/periods/{id}/": {
    get: operations["api_games_tournaments_matches_periods_retrieve"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/matches/{id}/": {
    get: operations["api_games_tournaments_matches_retrieve"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/matches/{id}/finish/": {
    post: operations["api_games_tournaments_matches_finish_create"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/stages/": {
    get: operations["api_games_tournaments_stages_list"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/stages/{id}/": {
    get: operations["api_games_tournaments_stages_retrieve"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/stages/{id}/finish/": {
    post: operations["api_games_tournaments_stages_finish_create"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/stages/{id}/start/": {
    post: operations["api_games_tournaments_stages_start_create"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/teams/": {
    get: operations["api_games_tournaments_teams_list"];
    post: operations["api_games_tournaments_teams_create"];
  };
  "/api/games/{game_pk}/tournaments/{tournament_pk}/teams/{id}/": {
    get: operations["api_games_tournaments_teams_retrieve"];
    put: operations["api_games_tournaments_teams_update"];
    delete: operations["api_games_tournaments_teams_destroy"];
    patch: operations["api_games_tournaments_teams_partial_update"];
  };
  "/api/games/{id}/": {
    get: operations["api_games_retrieve"];
  };
  "/api/teams/": {
    get: operations["api_teams_list"];
  };
  "/api/teams/{id}/": {
    get: operations["api_teams_retrieve"];
  };
  "/attachments/": {
    get: operations["attachments_list"];
    post: operations["attachments_create"];
  };
  "/attachments/{id}/": {
    get: operations["attachments_retrieve"];
    put: operations["attachments_update"];
    delete: operations["attachments_destroy"];
    patch: operations["attachments_partial_update"];
  };
  "/attachments/attachment-groups/": {
    get: operations["attachments_attachment_groups_list"];
  };
  "/attachments/attachment-groups/{id}/": {
    get: operations["attachments_attachment_groups_retrieve"];
  };
  "/attachments/attachment-groups/{id}/attachments/": {
    /** @description Action for update or delete attachments */
    put: operations["attachments_attachment_groups_attachments_update"];
    /** @description Action for update or delete attachments */
    delete: operations["attachments_attachment_groups_attachments_destroy"];
  };
  "/auth/login/": {
    /**
     * @description Check the credentials and return the REST Token
     * if the credentials are valid and authenticated.
     * Calls Django Auth login method to register User ID
     * in Django session framework
     *
     * Accept the following POST parameters: username, password
     * Return the REST Framework Token Object's key.
     */
    post: operations["auth_login_create"];
  };
  "/auth/logout/": {
    /**
     * @description Calls Django logout method and delete the Token object
     * assigned to the current User object.
     *
     * Accepts/Returns nothing.
     */
    post: operations["auth_logout_create"];
  };
  "/auth/password/change/": {
    /**
     * @description Calls Django Auth SetPasswordForm save method.
     *
     * Accepts the following POST parameters: new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["auth_password_change_create"];
  };
  "/auth/password/reset/": {
    /**
     * @description Calls Django Auth PasswordResetForm save method.
     *
     * Accepts the following POST parameters: email
     * Returns the success/fail message.
     */
    post: operations["auth_password_reset_create"];
  };
  "/auth/password/reset/confirm/": {
    /**
     * @description Password reset e-mail link is confirmed, therefore
     * this resets the user's password.
     *
     * Accepts the following POST parameters: token, uid,
     *     new_password1, new_password2
     * Returns the success/fail message.
     */
    post: operations["auth_password_reset_confirm_create"];
  };
  "/auth/registration/": {
    post: operations["auth_registration_create"];
  };
  "/auth/registration/resend-email/": {
    post: operations["auth_registration_resend_email_create"];
  };
  "/auth/registration/verify-email/": {
    post: operations["auth_registration_verify_email_create"];
  };
  "/auth/token/refresh/": {
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["auth_token_refresh_create"];
  };
  "/auth/token/verify/": {
    /**
     * @description Takes a token and indicates if it is valid.  This view provides no
     * information about a token's fitness for a particular use.
     */
    post: operations["auth_token_verify_create"];
  };
  "/auth/user/": {
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    get: operations["auth_user_retrieve"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    put: operations["auth_user_update"];
    /**
     * @description Reads and updates UserModel fields
     * Accepts GET, PUT, PATCH methods.
     *
     * Default accepted fields: username, first_name, last_name
     * Default display fields: pk, username, email, first_name, last_name
     * Read-only fields: pk, email
     *
     * Returns UserModel fields.
     */
    patch: operations["auth_user_partial_update"];
  };
  "/bot/": {
    post: operations["bot_create"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    AttachmentCreate: {
      id: number;
      /** Format: uri */
      file: string;
      mime_type: components["schemas"]["MimeTypeEnum"];
    };
    AttachmentGroupReadOnly: {
      id: number;
      /** @description type of AttachmentGroup */
      type: components["schemas"]["AttachmentGroupReadOnlyTypeEnum"];
      attachments: readonly components["schemas"]["AttachmentReadOnly"][];
    };
    /** @enum {string} */
    AttachmentGroupReadOnlyTypeEnum: "USER_AVATAR" | "WORKSPACE_AVATAR" | "SYSTEM_LOGO" | "CONNECTOR_LOGO" | "ENTITY_LOGO";
    AttachmentReadOnly: {
      id: number;
      /** Format: uri */
      file: string;
      created_by: number | null;
      /** Format: date-time */
      created: string;
    };
    /** @enum {string} */
    CountryEnum: "AF" | "AX" | "AL" | "DZ" | "AS" | "AD" | "AO" | "AI" | "AQ" | "AG" | "AR" | "AM" | "AW" | "AU" | "AT" | "AZ" | "BS" | "BH" | "BD" | "BB" | "BY" | "BE" | "BZ" | "BJ" | "BM" | "BT" | "BO" | "BQ" | "BA" | "BW" | "BV" | "BR" | "IO" | "BN" | "BG" | "BF" | "BI" | "CV" | "KH" | "CM" | "CA" | "KY" | "CF" | "TD" | "CL" | "CN" | "CX" | "CC" | "CO" | "KM" | "CG" | "CD" | "CK" | "CR" | "CI" | "HR" | "CU" | "CW" | "CY" | "CZ" | "DK" | "DJ" | "DM" | "DO" | "EC" | "EG" | "SV" | "GQ" | "ER" | "EE" | "SZ" | "ET" | "FK" | "FO" | "FJ" | "FI" | "FR" | "GF" | "PF" | "TF" | "GA" | "GM" | "GE" | "DE" | "GH" | "GI" | "GR" | "GL" | "GD" | "GP" | "GU" | "GT" | "GG" | "GN" | "GW" | "GY" | "HT" | "HM" | "VA" | "HN" | "HK" | "HU" | "IS" | "IN" | "ID" | "IR" | "IQ" | "IE" | "IM" | "IL" | "IT" | "JM" | "JP" | "JE" | "JO" | "KZ" | "KE" | "KI" | "KW" | "KG" | "LA" | "LV" | "LB" | "LS" | "LR" | "LY" | "LI" | "LT" | "LU" | "MO" | "MG" | "MW" | "MY" | "MV" | "ML" | "MT" | "MH" | "MQ" | "MR" | "MU" | "YT" | "MX" | "FM" | "MD" | "MC" | "MN" | "ME" | "MS" | "MA" | "MZ" | "MM" | "NA" | "NR" | "NP" | "NL" | "NC" | "NZ" | "NI" | "NE" | "NG" | "NU" | "NF" | "KP" | "MK" | "MP" | "NO" | "OM" | "PK" | "PW" | "PS" | "PA" | "PG" | "PY" | "PE" | "PH" | "PN" | "PL" | "PT" | "PR" | "QA" | "RE" | "RO" | "RU" | "RW" | "BL" | "SH" | "KN" | "LC" | "MF" | "PM" | "VC" | "WS" | "SM" | "ST" | "SA" | "SN" | "RS" | "SC" | "SL" | "SG" | "SX" | "SK" | "SI" | "SB" | "SO" | "ZA" | "GS" | "KR" | "SS" | "ES" | "LK" | "SD" | "SR" | "SJ" | "SE" | "CH" | "SY" | "TW" | "TJ" | "TZ" | "TH" | "TL" | "TG" | "TK" | "TO" | "TT" | "TN" | "TR" | "TM" | "TC" | "TV" | "UG" | "UA" | "AE" | "GB" | "UM" | "US" | "UY" | "UZ" | "VU" | "VE" | "VN" | "VG" | "VI" | "WF" | "EH" | "YE" | "ZM" | "ZW";
    GameReadOnly: {
      id: number;
      avatar: components["schemas"]["AttachmentReadOnly"];
      banner: components["schemas"]["AttachmentReadOnly"];
      header: components["schemas"]["AttachmentReadOnly"];
      name: string;
      description: string;
    };
    /** @enum {string} */
    GenderEnum: "FEMALE" | "MALE";
    /** @description Serializer for JWT authentication. */
    JWT: {
      access_token: string;
      refresh_token: string;
      user: components["schemas"]["User"];
    };
    /** @enum {string} */
    LanguageEnum: "af" | "ar" | "ast" | "az" | "bg" | "be" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "eo" | "es" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "uk" | "ur" | "uz" | "vi" | "us";
    Login: {
      username?: string;
      /** Format: email */
      email?: string;
      password: string;
    };
    MatchReadOnly: {
      id: number;
      status: components["schemas"]["StatusEnum"];
      scores: components["schemas"]["ScoreMatch"][];
      periods: components["schemas"]["PeriodReadOnly"][];
    };
    /** @enum {string} */
    MimeTypeEnum: "image/png" | "image/svg+xml" | "image/jpg" | "image/jpeg" | "image/webp";
    /** @enum {unknown} */
    NullEnum: "";
    PaginatedAttachmentGroupReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["AttachmentGroupReadOnly"][];
    };
    PaginatedAttachmentReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["AttachmentReadOnly"][];
    };
    PaginatedGameReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["GameReadOnly"][];
    };
    PaginatedPeriodReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["PeriodReadOnly"][];
    };
    PaginatedTeamReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["TeamReadOnly"][];
    };
    PaginatedTournamentReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["TournamentReadOnly"][];
    };
    PaginatedTournamentStageReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["TournamentStageReadOnly"][];
    };
    PaginatedTournamentTeamReadOnlyList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=400&limit=100
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?offset=200&limit=100
       */
      previous?: string | null;
      results?: components["schemas"]["TournamentTeamReadOnly"][];
    };
    PasswordChange: {
      new_password1: string;
      new_password2: string;
    };
    /** @description Serializer for requesting a password reset e-mail. */
    PasswordReset: {
      /** Format: email */
      email: string;
    };
    /** @description Serializer for confirming a password reset attempt. */
    PasswordResetConfirm: {
      new_password1: string;
      new_password2: string;
      uid: string;
      token: string;
    };
    PatchedAttachmentReadOnly: {
      id?: number;
      /** Format: uri */
      file?: string;
      created_by?: number | null;
      /** Format: date-time */
      created?: string;
    };
    PatchedTeamScore: {
      team?: number;
      /** Format: double */
      value?: number;
      period?: number;
    };
    PatchedTournamentTeamUpdate: {
      is_confirmed?: boolean;
    };
    PatchedUser: {
      id?: number;
      /**
       * Email address
       * Format: email
       */
      email?: string;
      first_name?: string;
      country?: components["schemas"]["CountryEnum"];
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      is_staff?: boolean;
      last_name?: string;
      /** Format: date */
      birth_day?: string | null;
      gender?: components["schemas"]["GenderEnum"] | components["schemas"]["NullEnum"] | null;
      avatar?: components["schemas"]["AttachmentReadOnly"] | null;
      avatar_id?: number | null;
      language?: components["schemas"]["LanguageEnum"];
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username?: string;
      real_currency?: number;
      virtual_currency?: number;
      battle_tag?: string | null;
    };
    PeriodReadOnly: {
      id: number;
      team_scores: components["schemas"]["TeamScoreReadOnly"][];
    };
    Register: {
      username: string;
      /** Format: email */
      email: string;
      password1: string;
      password2: string;
    };
    ResendEmailVerification: {
      /** Format: email */
      email: string;
    };
    RestAuthDetail: {
      detail: string;
    };
    ScoreMatch: {
      team_id: number;
      team_name: string;
      /** Format: double */
      sum: number;
    };
    /** @enum {string} */
    StatusEnum: "BYE" | "NOT_STARTED" | "STARTED" | "FINISHED";
    TeamReadOnly: {
      id: number;
      name: string;
      avatar: components["schemas"]["AttachmentReadOnly"];
      users: components["schemas"]["User"][];
    };
    TeamScore: {
      team: number;
      /** Format: double */
      value: number;
      period: number;
    };
    TeamScoreReadOnly: {
      id: number;
      team: components["schemas"]["TeamReadOnly"];
      /** Format: double */
      value: number;
      period: number;
    };
    TokenRefresh: {
      access: string;
      refresh: string;
    };
    TokenVerify: {
      token: string;
    };
    TournamentReadOnly: {
      id: number;
      name: string;
      game: components["schemas"]["GameReadOnly"];
      teams: components["schemas"]["TeamReadOnly"][];
      type: components["schemas"]["TournamentReadOnlyTypeEnum"];
      teams_in_match: number;
      winners_in_match_count: number;
      prizes: {
        [key: string]: unknown;
      };
      description: string | null;
      rules: string | null;
      /** Format: date-time */
      start_at: string;
      max_teams: number;
      min_teams: number;
      avatar: components["schemas"]["AttachmentReadOnly"];
      stage_schedule: {
          [key: string]: unknown;
        }[];
      schedule: {
          [key: string]: unknown;
        }[];
      stage_formats: number[];
      teams_by_place: components["schemas"]["ScoreMatch"][];
      stream_url: string | null;
    };
    /** @enum {string} */
    TournamentReadOnlyTypeEnum: "BO1";
    TournamentStageReadOnly: {
      id: number;
      order: number;
      matches: readonly number[];
    };
    TournamentTeamCreate: {
      tournament: number;
      team: number;
    };
    TournamentTeamReadOnly: {
      id: number;
      team: components["schemas"]["TeamReadOnly"];
      place: number | null;
      is_confirmed: boolean;
    };
    TournamentTeamUpdate: {
      is_confirmed?: boolean;
    };
    User: {
      id: number;
      /**
       * Email address
       * Format: email
       */
      email?: string;
      first_name?: string;
      country: components["schemas"]["CountryEnum"];
      /**
       * Staff status
       * @description Designates whether the user can log into this admin site.
       */
      is_staff?: boolean;
      last_name?: string;
      /** Format: date */
      birth_day?: string | null;
      gender?: components["schemas"]["GenderEnum"] | components["schemas"]["NullEnum"] | null;
      avatar: components["schemas"]["AttachmentReadOnly"] | null;
      avatar_id: number | null;
      language?: components["schemas"]["LanguageEnum"];
      /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
      username: string;
      real_currency?: number;
      virtual_currency?: number;
      battle_tag?: string | null;
    };
    VerifyEmail: {
      key: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  api_attachments_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAttachmentReadOnlyList"];
        };
      };
    };
  };
  api_attachments_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttachmentCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentCreate"];
        "multipart/form-data": components["schemas"]["AttachmentCreate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AttachmentCreate"];
        };
      };
    };
  };
  api_attachments_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  api_attachments_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AttachmentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentReadOnly"];
        "multipart/form-data": components["schemas"]["AttachmentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  api_attachments_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_attachments_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedAttachmentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachmentReadOnly"];
        "multipart/form-data": components["schemas"]["PatchedAttachmentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  api_attachments_attachment_groups_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAttachmentGroupReadOnlyList"];
        };
      };
    };
  };
  api_attachments_attachment_groups_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        };
      };
    };
  };
  /** @description Action for update or delete attachments */
  api_attachments_attachment_groups_attachments_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentGroupReadOnly"];
        "multipart/form-data": components["schemas"]["AttachmentGroupReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        };
      };
    };
  };
  /** @description Action for update or delete attachments */
  api_attachments_attachment_groups_attachments_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * @description Check the credentials and return the REST Token
   * if the credentials are valid and authenticated.
   * Calls Django Auth login method to register User ID
   * in Django session framework
   *
   * Accept the following POST parameters: username, password
   * Return the REST Framework Token Object's key.
   */
  api_auth_login_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
        "application/x-www-form-urlencoded": components["schemas"]["Login"];
        "multipart/form-data": components["schemas"]["Login"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JWT"];
        };
      };
    };
  };
  /**
   * @description Calls Django logout method and delete the Token object
   * assigned to the current User object.
   *
   * Accepts/Returns nothing.
   */
  api_auth_logout_create: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth SetPasswordForm save method.
   *
   * Accepts the following POST parameters: new_password1, new_password2
   * Returns the success/fail message.
   */
  api_auth_password_change_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth PasswordResetForm save method.
   *
   * Accepts the following POST parameters: email
   * Returns the success/fail message.
   */
  api_auth_password_reset_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordReset"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
        "multipart/form-data": components["schemas"]["PasswordReset"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Password reset e-mail link is confirmed, therefore
   * this resets the user's password.
   *
   * Accepts the following POST parameters: token, uid,
   *     new_password1, new_password2
   * Returns the success/fail message.
   */
  api_auth_password_reset_confirm_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
        "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  api_auth_registration_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Register"];
        "application/x-www-form-urlencoded": components["schemas"]["Register"];
        "multipart/form-data": components["schemas"]["Register"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["JWT"];
        };
      };
    };
  };
  api_auth_registration_resend_email_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendEmailVerification"];
        "application/x-www-form-urlencoded": components["schemas"]["ResendEmailVerification"];
        "multipart/form-data": components["schemas"]["ResendEmailVerification"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  api_auth_registration_verify_email_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmail"];
        "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
        "multipart/form-data": components["schemas"]["VerifyEmail"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  api_auth_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  /**
   * @description Takes a token and indicates if it is valid.  This view provides no
   * information about a token's fitness for a particular use.
   */
  api_auth_token_verify_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenVerify"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
        "multipart/form-data": components["schemas"]["TokenVerify"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenVerify"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  api_auth_user_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  api_auth_user_update: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
        "application/x-www-form-urlencoded": components["schemas"]["User"];
        "multipart/form-data": components["schemas"]["User"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  api_auth_user_partial_update: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUser"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
        "multipart/form-data": components["schemas"]["PatchedUser"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  api_bot_create: {
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
  api_games_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedGameReadOnlyList"];
        };
      };
    };
  };
  api_games_tournaments_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
      path: {
        game_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedTournamentReadOnlyList"];
        };
      };
    };
  };
  api_games_tournaments_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_finish_create: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TournamentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentReadOnly"];
        "multipart/form-data": components["schemas"]["TournamentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentReadOnly"];
        };
      };
    };
  };
  /** @description Returns scores for tournament */
  api_games_tournaments_scores_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_start_create: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TournamentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentReadOnly"];
        "multipart/form-data": components["schemas"]["TournamentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_matches_periods_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
      path: {
        game_pk: string;
        match_pk: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedPeriodReadOnlyList"];
        };
      };
    };
  };
  api_games_tournaments_matches_periods_scores_update: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        match_pk: string;
        period_pk: string;
        tournament_pk: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TeamScore"];
        "application/x-www-form-urlencoded": components["schemas"]["TeamScore"];
        "multipart/form-data": components["schemas"]["TeamScore"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TeamScore"];
        };
      };
    };
  };
  api_games_tournaments_matches_periods_scores_partial_update: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        match_pk: string;
        period_pk: string;
        tournament_pk: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedTeamScore"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedTeamScore"];
        "multipart/form-data": components["schemas"]["PatchedTeamScore"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TeamScore"];
        };
      };
    };
  };
  api_games_tournaments_matches_periods_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        match_pk: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PeriodReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_matches_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        /** @description A unique integer value identifying this match. */
        id: number;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MatchReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_matches_finish_create: {
    parameters: {
      path: {
        game_pk: string;
        /** @description A unique integer value identifying this match. */
        id: number;
        tournament_pk: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MatchReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["MatchReadOnly"];
        "multipart/form-data": components["schemas"]["MatchReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MatchReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_stages_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
      path: {
        game_pk: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedTournamentStageReadOnlyList"];
        };
      };
    };
  };
  api_games_tournaments_stages_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentStageReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_stages_finish_create: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TournamentStageReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentStageReadOnly"];
        "multipart/form-data": components["schemas"]["TournamentStageReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentStageReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_stages_start_create: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TournamentStageReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentStageReadOnly"];
        "multipart/form-data": components["schemas"]["TournamentStageReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentStageReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_teams_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
      path: {
        game_pk: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedTournamentTeamReadOnlyList"];
        };
      };
    };
  };
  api_games_tournaments_teams_create: {
    parameters: {
      path: {
        game_pk: string;
        tournament_pk: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TournamentTeamCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentTeamCreate"];
        "multipart/form-data": components["schemas"]["TournamentTeamCreate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["TournamentTeamCreate"];
        };
      };
    };
  };
  api_games_tournaments_teams_retrieve: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentTeamReadOnly"];
        };
      };
    };
  };
  api_games_tournaments_teams_update: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["TournamentTeamUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["TournamentTeamUpdate"];
        "multipart/form-data": components["schemas"]["TournamentTeamUpdate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentTeamUpdate"];
        };
      };
    };
  };
  api_games_tournaments_teams_destroy: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_games_tournaments_teams_partial_update: {
    parameters: {
      path: {
        game_pk: string;
        id: string;
        tournament_pk: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedTournamentTeamUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedTournamentTeamUpdate"];
        "multipart/form-data": components["schemas"]["PatchedTournamentTeamUpdate"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TournamentTeamUpdate"];
        };
      };
    };
  };
  api_games_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this game. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["GameReadOnly"];
        };
      };
    };
  };
  api_teams_list: {
    parameters: {
      query?: {
        id?: number;
        id__in?: number[];
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
        users?: number[];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedTeamReadOnlyList"];
        };
      };
    };
  };
  api_teams_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this team. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TeamReadOnly"];
        };
      };
    };
  };
  attachments_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAttachmentReadOnlyList"];
        };
      };
    };
  };
  attachments_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttachmentCreate"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentCreate"];
        "multipart/form-data": components["schemas"]["AttachmentCreate"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["AttachmentCreate"];
        };
      };
    };
  };
  attachments_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  attachments_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AttachmentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentReadOnly"];
        "multipart/form-data": components["schemas"]["AttachmentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  attachments_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  attachments_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedAttachmentReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedAttachmentReadOnly"];
        "multipart/form-data": components["schemas"]["PatchedAttachmentReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentReadOnly"];
        };
      };
    };
  };
  attachments_attachment_groups_list: {
    parameters: {
      query?: {
        /** @description Number of results to return per page. */
        limit?: number;
        /** @description The initial index from which to return the results. */
        offset?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedAttachmentGroupReadOnlyList"];
        };
      };
    };
  };
  attachments_attachment_groups_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        };
      };
    };
  };
  /** @description Action for update or delete attachments */
  attachments_attachment_groups_attachments_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        "application/x-www-form-urlencoded": components["schemas"]["AttachmentGroupReadOnly"];
        "multipart/form-data": components["schemas"]["AttachmentGroupReadOnly"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentGroupReadOnly"];
        };
      };
    };
  };
  /** @description Action for update or delete attachments */
  attachments_attachment_groups_attachments_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this attachment group. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  /**
   * @description Check the credentials and return the REST Token
   * if the credentials are valid and authenticated.
   * Calls Django Auth login method to register User ID
   * in Django session framework
   *
   * Accept the following POST parameters: username, password
   * Return the REST Framework Token Object's key.
   */
  auth_login_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Login"];
        "application/x-www-form-urlencoded": components["schemas"]["Login"];
        "multipart/form-data": components["schemas"]["Login"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["JWT"];
        };
      };
    };
  };
  /**
   * @description Calls Django logout method and delete the Token object
   * assigned to the current User object.
   *
   * Accepts/Returns nothing.
   */
  auth_logout_create: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth SetPasswordForm save method.
   *
   * Accepts the following POST parameters: new_password1, new_password2
   * Returns the success/fail message.
   */
  auth_password_change_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Calls Django Auth PasswordResetForm save method.
   *
   * Accepts the following POST parameters: email
   * Returns the success/fail message.
   */
  auth_password_reset_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordReset"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
        "multipart/form-data": components["schemas"]["PasswordReset"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Password reset e-mail link is confirmed, therefore
   * this resets the user's password.
   *
   * Accepts the following POST parameters: token, uid,
   *     new_password1, new_password2
   * Returns the success/fail message.
   */
  auth_password_reset_confirm_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
        "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  auth_registration_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Register"];
        "application/x-www-form-urlencoded": components["schemas"]["Register"];
        "multipart/form-data": components["schemas"]["Register"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["JWT"];
        };
      };
    };
  };
  auth_registration_resend_email_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResendEmailVerification"];
        "application/x-www-form-urlencoded": components["schemas"]["ResendEmailVerification"];
        "multipart/form-data": components["schemas"]["ResendEmailVerification"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  auth_registration_verify_email_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["VerifyEmail"];
        "application/x-www-form-urlencoded": components["schemas"]["VerifyEmail"];
        "multipart/form-data": components["schemas"]["VerifyEmail"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["RestAuthDetail"];
        };
      };
    };
  };
  /**
   * @description Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  auth_token_refresh_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  /**
   * @description Takes a token and indicates if it is valid.  This view provides no
   * information about a token's fitness for a particular use.
   */
  auth_token_verify_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenVerify"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenVerify"];
        "multipart/form-data": components["schemas"]["TokenVerify"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TokenVerify"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_update: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["User"];
        "application/x-www-form-urlencoded": components["schemas"]["User"];
        "multipart/form-data": components["schemas"]["User"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  /**
   * @description Reads and updates UserModel fields
   * Accepts GET, PUT, PATCH methods.
   *
   * Default accepted fields: username, first_name, last_name
   * Default display fields: pk, username, email, first_name, last_name
   * Read-only fields: pk, email
   *
   * Returns UserModel fields.
   */
  auth_user_partial_update: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedUser"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedUser"];
        "multipart/form-data": components["schemas"]["PatchedUser"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  bot_create: {
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
}
